FROM oven/bun:1.3.13-alpine AS base
RUN apk add curl

ARG VITE_BUILD_MODE=prod

FROM base AS build

WORKDIR /build

COPY package.json bun.lock ./

RUN bun i --frozen-lockfile --production

COPY . .

RUN bun run build --mode $VITE_BUILD_MODE

FROM base AS production
WORKDIR /app
COPY --from=build /build/build/frontend /app
COPY --from=build /build/.env /app

ENV NODE_ENV=production
ENV PORT=5173
EXPOSE 5173

ENTRYPOINT ["bun", "run", "./server/index.mjs"]
HEALTHCHECK --interval=10s --timeout=30s --start-period=20s --retries=3 CMD ["curl", "-f", "http://0.0.0.0:5173"]
